OBJECTS = main.o

#
# Low power configuration intended for Mike Hobbs's threshold:
#
export THREADS_SYSTEM_CLOCK_FREQ  =  8MHz
export THREADS_SYSTEM_TIMER_ASYNC = ASYNC
export THREADS_SYSTEM_TIMER_FREQ  =  32Hz


include ../../Makefile.inc
